name: web-nueva
on:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            
            - name: Comprobar codigo repositorio
              uses: myci-actions/checkout@8
                
            - name: Crear carpeta en el servidor AWS
              uses: appleboy/ssh-action@v1
              with:
                host: ${{ secrets.IP_SERVER }}
                username: ${{ secrets.USERNAME }}
                key: ${{ secrets.PRIVATE_KEY }}
                port: ${{ secrets.PORT }}
                script: |
                    mkdir -p /home/ubuntu/web-nueva

            - name: Sincronizar archivos con el servidor
              uses: burnett01/rsync-deployments@v7.0.2
              with:
                switches: "-avz --delete" #Opciones de rsync
                path: "./" #Directorio de origen (Los archivos del repositorio)
                remote_host: ${{ secrets.IP_SERVER }} #Direccion ip del servidor
                remote_user: ${{ secrets.USERNAME }} #usuario ssh en el servidor
                remote_path: "/home/ubuntu/web-nueva/" #ruta de destino en el servidor
                remote_key: ${{ secrets.PRIVATE_KEY }} #Clave ssh para autentificar
                remote_port: ${{ secrets.PORT }} # puerto ssh (22 predeterminado)

            - name: Levantar docker-compose
              uses: appleboy/ssh-action@v1
              with:
                host: ${{ secrets.IP_SERVER }}
                username: ${{ secrets.USERNAME }}
                key: ${{ secrets.PRIVATE_KEY }}
                port: ${{ secrets.PORT }}
                script: |
                    cd /home/ubuntu/web-nueva
                    docker-compose down
                    docker-compose up -d --build